#!/usr/bin/env bash
set -euo pipefail

VERBOSE=0
if (( $# > 0 )) ; then
    case "$1" in
        "")
            : ;;
        -v|--verbose)
            VERBOSE=1
            ;;
        *)
            echo "usage: $(basename $0) [-v|--verbose]"
            exit 0
            ;;
    esac
fi

cd $(dirname $0)
./brew-list-reverse-dependencies |
    sed -lne '/:$/s/://p' |
    while read formula ; do
        if ! grep -q -s "${formula}" Brewfile ; then
            echo "${formula}"
        elif (( ${VERBOSE} == 1 )) ; then
            echo "${formula} (in Brewfile)"
        fi
    done
