# vim: set filetype=ruby :

brew "abduco"
brew "bash"
brew "bash-completion@2"
brew "black"
brew "btop"
brew "ca-certificates"
brew "clang-format"
brew "ctags"
brew "exiftool"
brew "ffmpeg"
brew "flac"
brew "gh" # github
brew "git-lfs"
brew "gitui"
brew "go"
brew "lame"
brew "ipcalc"
brew "isync"
brew "jq"
brew "mas"  # Mac App Store cli
brew "pandoc"
brew "pssh"
brew "pstree"
brew "python"
brew "python-packaging"
# pyyaml removed in https://github.com/Homebrew/homebrew-core/pull/176591
#brew "pyyaml"
brew "rclone"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "shfmt"
brew "vim"
brew "watch"
brew "wget"
# Disabled upstream in Homebrew
#brew "youtube-dl"

cask "font-dejavu"
cask "font-hack"
cask "font-input"

RestrictedItems = {
  "mactex-no-gui" => {
    :type => :cask,
    :sudo => true,
    :work => false,
  },
  # https://github.com/jordanbaird/Ice
  # https://icemenubar.app/
  "jordanbaird-ice@beta" => {
    :type => :cask,
    :sudo => true,
    :work => true,
  },
  "lookaway" => {
    :type => :cask,
    :sudo => true,
    :work => true,
  },
}

CanSudo = (Process.gid == 80) || (Process.groups.include? 80)
IsWork = ["/Library/HDS", "/usr/local/hitachi", "/usr/local/jamf"].any? { |d| File.exist? d }
MachineType = IsWork ? "work" : "non-work"

RestrictedItems.each() { |name,details|
  if details[:sudo] && !CanSudo
    $stderr.puts("Warning: Not installing #{name} which needs sudo")
    next
  end
  if details[:work] != IsWork
    $stderr.puts("Warning: Not installing #{name} on #{MachineType} machine")
    next
  end
  send(details[:type], name)
}
