#!/usr/bin/env bash
set -euo pipefail

brew list --formulae -1 |
while read formula ; do
    echo -n "${formula}:"
    brew uses ${formula} --installed | awk '{ printf(" %s", $0) }' -
    echo ""
done
